PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityResult> .
    optional{ ?resource sphn:hasCode ?Code . }
    optional{ ?resource sphn:hasQuantity ?Quantity . }
    optional{ ?resource sphn:hasQuantity/sphn:hasValue ?Quantity_Value . }
    optional{ ?resource sphn:hasQuantity/sphn:hasUnit ?Quantity_Unit . }
    optional{ ?resource sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?Quantity_Unit_Code . }
    optional{ ?resource sphn:hasQuantity/sphn:hasComparator ?Quantity_Comparator . }
    optional{ ?resource sphn:hasStandardGuideline ?StandardGuideline . }
    optional{ ?resource sphn:hasStringValue ?StringValue . }
    optional{ ?resource sphn:hasNumericalReference ?NumericalReference . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity ?NumericalReference_Quantity . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasValue ?NumericalReference_Quantity_Value . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit ?NumericalReference_Quantity_Unit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?NumericalReference_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasComparator ?NumericalReference_Quantity_Comparator . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit ?NumericalReference_LowerLimit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasValue ?NumericalReference_LowerLimit_Value . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit ?NumericalReference_LowerLimit_Unit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode ?NumericalReference_LowerLimit_Unit_Code . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasComparator ?NumericalReference_LowerLimit_Comparator . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit ?NumericalReference_UpperLimit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasValue ?NumericalReference_UpperLimit_Value . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit ?NumericalReference_UpperLimit_Unit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode ?NumericalReference_UpperLimit_Unit_Code . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasComparator ?NumericalReference_UpperLimit_Comparator . }

}