PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AssessmentComponent> .
    optional{ ?resource sphn:hasName ?Name . }
    optional{ ?resource sphn:hasCode ?Code . }
    optional{ ?resource sphn:hasResult ?Result . }
    optional{ ?resource sphn:hasResult/sphn:hasCode ?Result_Code . }
    optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasName ?Result_Code_Name . }
    optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasIdentifier ?Result_Code_Identifier . }
    optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasCodingSystemAndVersion ?Result_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity ?Result_Quantity . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasValue ?Result_Quantity_Value . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit ?Result_Quantity_Unit . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?Result_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasComparator ?Result_Quantity_Comparator . }
    optional{ ?resource sphn:hasResult/sphn:hasStringValue ?Result_StringValue . }

}