PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#CircumferenceMeasurement> .
    optional{ ?resource sphn:hasDataProvider ?DataProvider . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment ?DataProvider_Department . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode ?DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasCategory ?DataProvider_Category . }
    optional{ ?resource sphn:hasBodySite ?BodySite . }
    optional{ ?resource sphn:hasBodySite/sphn:hasCode ?BodySite_Code . }
    optional{ ?resource sphn:hasBodySite/sphn:hasLaterality ?BodySite_Laterality . }
    optional{ ?resource sphn:hasBodySite/sphn:hasLaterality/sphn:hasCode ?BodySite_Laterality_Code . }
    optional{ ?resource sphn:hasSourceSystem ?SourceSystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasName ?SourceSystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider ?SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem ?SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasCategory ?SourceSystem_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPurpose ?SourceSystem_Purpose . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier ?SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasResult ?Result . }
    optional{ ?resource sphn:hasResult/sphn:hasDateTime ?Result_DateTime . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity ?Result_Quantity . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasValue ?Result_Quantity_Value . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit ?Result_Quantity_Unit . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?Result_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasComparator ?Result_Quantity_Comparator . }
    optional{ ?resource sphn:hasMethodCode ?MethodCode . }
    optional{ ?resource sphn:hasAdministrativeCase ?AdministrativeCase . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime ?AdministrativeCase_AdmissionDateTime . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeDateTime ?AdministrativeCase_DischargeDateTime . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasIdentifier ?AdministrativeCase_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider ?AdministrativeCase_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling ?AdministrativeCase_CareHandling . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem ?AdministrativeCase_CareHandling_SourceSystem . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider ?AdministrativeCase_CareHandling_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasCategory ?AdministrativeCase_CareHandling_SourceSystem_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPurpose ?AdministrativeCase_CareHandling_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasTypeCode ?AdministrativeCase_CareHandling_TypeCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation ?AdministrativeCase_DischargeLocation . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasExact ?AdministrativeCase_DischargeLocation_Exact . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider ?AdministrativeCase_DischargeLocation_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_DischargeLocation_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_DischargeLocation_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_DischargeLocation_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasTypeCode ?AdministrativeCase_DischargeLocation_TypeCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem ?AdministrativeCase_SourceSystem . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasName ?AdministrativeCase_SourceSystem_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider ?AdministrativeCase_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem ?AdministrativeCase_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?AdministrativeCase_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?AdministrativeCase_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasCategory ?AdministrativeCase_SourceSystem_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPurpose ?AdministrativeCase_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier ?AdministrativeCase_SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?AdministrativeCase_SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?AdministrativeCase_SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation ?AdministrativeCase_OriginLocation . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasExact ?AdministrativeCase_OriginLocation_Exact . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider ?AdministrativeCase_OriginLocation_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_OriginLocation_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_OriginLocation_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_OriginLocation_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_OriginLocation_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasTypeCode ?AdministrativeCase_OriginLocation_TypeCode . }
    optional{ ?resource sphn:hasPerformer ?Performer . }
    optional{ ?resource sphn:hasPerformer/sphn:hasCode ?Performer_Code . }
    optional{ ?resource sphn:hasStartDateTime ?StartDateTime . }
    optional{ ?resource sphn:hasEndDateTime ?EndDateTime . }
    optional{ ?resource sphn:hasMedicalDevice ?MedicalDevice . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasTypeCode ?MedicalDevice_TypeCode . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasTypeCode/sphn:hasName ?MedicalDevice_TypeCode_Name . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasTypeCode/sphn:hasIdentifier ?MedicalDevice_TypeCode_Identifier . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?MedicalDevice_TypeCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware ?MedicalDevice_Software . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasName ?MedicalDevice_Software_Name . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasUniformResourceLocator ?MedicalDevice_Software_UniformResourceLocator . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDataProvider ?MedicalDevice_Software_DataProvider . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment ?MedicalDevice_Software_DataProvider_Department . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?MedicalDevice_Software_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?MedicalDevice_Software_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?MedicalDevice_Software_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?MedicalDevice_Software_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?MedicalDevice_Software_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory ?MedicalDevice_Software_DataProvider_Category . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasDescription ?MedicalDevice_Software_Description . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasSoftware/sphn:hasVersion ?MedicalDevice_Software_Version . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasProductCode ?MedicalDevice_ProductCode . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasProductCode/sphn:hasName ?MedicalDevice_ProductCode_Name . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasProductCode/sphn:hasIdentifier ?MedicalDevice_ProductCode_Identifier . }
    optional{ ?resource sphn:hasMedicalDevice/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?MedicalDevice_ProductCode_CodingSystemAndVersion . }

}