PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#CivilStatus> .
    optional{ ?resource sphn:hasEventDateTime ?EventDateTime . }
    optional{ ?resource sphn:hasCode ?Code . }
    optional{ ?resource sphn:hasSourceSystem ?SourceSystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasName ?SourceSystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider ?SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem ?SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasCategory ?SourceSystem_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPurpose ?SourceSystem_Purpose . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier ?SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?SubjectPseudoIdentifier_DataProvider_Category . }

}