PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DataProvider> .
    optional{ ?resource sphn:hasDepartment ?Department . }
    optional{ ?resource sphn:hasDepartment/sphn:hasName ?Department_Name . }
    optional{ ?resource sphn:hasInstitutionCode ?InstitutionCode . }
    optional{ ?resource sphn:hasInstitutionCode/sphn:hasName ?InstitutionCode_Name . }
    optional{ ?resource sphn:hasInstitutionCode/sphn:hasIdentifier ?InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasCategory ?Category . }

}