PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#Drug> .
    optional{ ?resource sphn:hasActiveIngredient ?ActiveIngredient . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasGenericName ?ActiveIngredient_GenericName . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasCode ?ActiveIngredient_Code . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasCode/sphn:hasName ?ActiveIngredient_Code_Name . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasCode/sphn:hasIdentifier ?ActiveIngredient_Code_Identifier . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasCode/sphn:hasCodingSystemAndVersion ?ActiveIngredient_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasQuantity ?ActiveIngredient_Quantity . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasValue ?ActiveIngredient_Quantity_Value . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasUnit ?ActiveIngredient_Quantity_Unit . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?ActiveIngredient_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasComparator ?ActiveIngredient_Quantity_Comparator . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem ?ActiveIngredient_SourceSystem . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasName ?ActiveIngredient_SourceSystem_Name . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider ?ActiveIngredient_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?ActiveIngredient_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?ActiveIngredient_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?ActiveIngredient_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?ActiveIngredient_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?ActiveIngredient_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?ActiveIngredient_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?ActiveIngredient_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem ?ActiveIngredient_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?ActiveIngredient_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?ActiveIngredient_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?ActiveIngredient_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?ActiveIngredient_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?ActiveIngredient_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?ActiveIngredient_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?ActiveIngredient_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?ActiveIngredient_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?ActiveIngredient_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?ActiveIngredient_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasCategory ?ActiveIngredient_SourceSystem_Category . }
    optional{ ?resource sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPurpose ?ActiveIngredient_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasInactiveIngredient ?InactiveIngredient . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasGenericName ?InactiveIngredient_GenericName . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasCode ?InactiveIngredient_Code . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasCode/sphn:hasName ?InactiveIngredient_Code_Name . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasCode/sphn:hasIdentifier ?InactiveIngredient_Code_Identifier . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasCode/sphn:hasCodingSystemAndVersion ?InactiveIngredient_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasQuantity ?InactiveIngredient_Quantity . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasValue ?InactiveIngredient_Quantity_Value . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasUnit ?InactiveIngredient_Quantity_Unit . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?InactiveIngredient_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasComparator ?InactiveIngredient_Quantity_Comparator . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem ?InactiveIngredient_SourceSystem . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasName ?InactiveIngredient_SourceSystem_Name . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider ?InactiveIngredient_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?InactiveIngredient_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?InactiveIngredient_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?InactiveIngredient_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?InactiveIngredient_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?InactiveIngredient_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?InactiveIngredient_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?InactiveIngredient_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem ?InactiveIngredient_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?InactiveIngredient_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?InactiveIngredient_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?InactiveIngredient_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?InactiveIngredient_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?InactiveIngredient_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?InactiveIngredient_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?InactiveIngredient_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?InactiveIngredient_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?InactiveIngredient_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?InactiveIngredient_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasCategory ?InactiveIngredient_SourceSystem_Category . }
    optional{ ?resource sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPurpose ?InactiveIngredient_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasArticle ?Article . }
    optional{ ?resource sphn:hasArticle/sphn:hasName ?Article_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasCode ?Article_Code . }
    optional{ ?resource sphn:hasArticle/sphn:hasCode/sphn:hasName ?Article_Code_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasCode/sphn:hasIdentifier ?Article_Code_Identifier . }
    optional{ ?resource sphn:hasArticle/sphn:hasCode/sphn:hasCodingSystemAndVersion ?Article_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasArticle/sphn:hasManufacturedDoseForm ?Article_ManufacturedDoseForm . }
    optional{ ?resource sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode ?Article_ManufacturedDoseForm_Code . }
    optional{ ?resource sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode/sphn:hasName ?Article_ManufacturedDoseForm_Code_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode/sphn:hasIdentifier ?Article_ManufacturedDoseForm_Code_Identifier . }
    optional{ ?resource sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode/sphn:hasCodingSystemAndVersion ?Article_ManufacturedDoseForm_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem ?Article_SourceSystem . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasName ?Article_SourceSystem_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider ?Article_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?Article_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Article_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Article_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Article_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Article_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Article_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?Article_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem ?Article_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?Article_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?Article_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?Article_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?Article_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Article_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Article_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Article_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Article_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Article_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?Article_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasCategory ?Article_SourceSystem_Category . }
    optional{ ?resource sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPurpose ?Article_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasQuantity ?Quantity . }
    optional{ ?resource sphn:hasQuantity/sphn:hasValue ?Quantity_Value . }
    optional{ ?resource sphn:hasQuantity/sphn:hasUnit ?Quantity_Unit . }
    optional{ ?resource sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?Quantity_Unit_Code . }
    optional{ ?resource sphn:hasQuantity/sphn:hasComparator ?Quantity_Comparator . }
    optional{ ?resource sphn:hasSourceSystem ?SourceSystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasName ?SourceSystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider ?SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem ?SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasCategory ?SourceSystem_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPurpose ?SourceSystem_Purpose . }

}