PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#GenomicPosition> .
    optional{ ?resource sphn:hasEnd ?End . }
    optional{ ?resource sphn:hasStart ?Start . }
    optional{ ?resource sphn:hasCoordinateConvention ?CoordinateConvention . }
    optional{ ?resource sphn:hasReference ?Reference . }
    optional{ ?resource sphn:hasReference/sphn:hasCode ?Reference_Code . }
    optional{ ?resource sphn:hasReference/sphn:hasCode/sphn:hasName ?Reference_Code_Name . }
    optional{ ?resource sphn:hasReference/sphn:hasCode/sphn:hasIdentifier ?Reference_Code_Identifier . }
    optional{ ?resource sphn:hasReference/sphn:hasCode/sphn:hasCodingSystemAndVersion ?Reference_Code_CodingSystemAndVersion . }

}