PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#LabTest> .
    optional{ ?resource sphn:hasCode ?Code . }
    optional{ ?resource sphn:hasResult ?Result . }
    optional{ ?resource sphn:hasResult/sphn:hasCode ?Result_Code . }
    optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasName ?Result_Code_Name . }
    optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasIdentifier ?Result_Code_Identifier . }
    optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasCodingSystemAndVersion ?Result_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity ?Result_Quantity . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasValue ?Result_Quantity_Value . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit ?Result_Quantity_Unit . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?Result_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasComparator ?Result_Quantity_Comparator . }
    optional{ ?resource sphn:hasResult/sphn:hasStringValue ?Result_StringValue . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference ?Result_NumericalReference . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity ?Result_NumericalReference_Quantity . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasValue ?Result_NumericalReference_Quantity_Value . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit ?Result_NumericalReference_Quantity_Unit . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?Result_NumericalReference_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasComparator ?Result_NumericalReference_Quantity_Comparator . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit ?Result_NumericalReference_LowerLimit . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasValue ?Result_NumericalReference_LowerLimit_Value . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit ?Result_NumericalReference_LowerLimit_Unit . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode ?Result_NumericalReference_LowerLimit_Unit_Code . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasComparator ?Result_NumericalReference_LowerLimit_Comparator . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit ?Result_NumericalReference_UpperLimit . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasValue ?Result_NumericalReference_UpperLimit_Value . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit ?Result_NumericalReference_UpperLimit_Unit . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode ?Result_NumericalReference_UpperLimit_Unit_Code . }
    optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasComparator ?Result_NumericalReference_UpperLimit_Comparator . }
    optional{ ?resource sphn:hasInstrument ?Instrument . }
    optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode ?Instrument_TypeCode . }
    optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasName ?Instrument_TypeCode_Name . }
    optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasIdentifier ?Instrument_TypeCode_Identifier . }
    optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?Instrument_TypeCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware ?Instrument_Software . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasName ?Instrument_Software_Name . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasUniformResourceLocator ?Instrument_Software_UniformResourceLocator . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider ?Instrument_Software_DataProvider . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment ?Instrument_Software_DataProvider_Department . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Instrument_Software_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?Instrument_Software_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Instrument_Software_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Instrument_Software_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Instrument_Software_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory ?Instrument_Software_DataProvider_Category . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDescription ?Instrument_Software_Description . }
    optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasVersion ?Instrument_Software_Version . }
    optional{ ?resource sphn:hasInstrument/sphn:hasProductCode ?Instrument_ProductCode . }
    optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasName ?Instrument_ProductCode_Name . }
    optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasIdentifier ?Instrument_ProductCode_Identifier . }
    optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?Instrument_ProductCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasTestKit ?TestKit . }
    optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode ?TestKit_TypeCode . }
    optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasName ?TestKit_TypeCode_Name . }
    optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasIdentifier ?TestKit_TypeCode_Identifier . }
    optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?TestKit_TypeCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware ?TestKit_Software . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasName ?TestKit_Software_Name . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasUniformResourceLocator ?TestKit_Software_UniformResourceLocator . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider ?TestKit_Software_DataProvider . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment ?TestKit_Software_DataProvider_Department . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?TestKit_Software_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?TestKit_Software_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?TestKit_Software_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?TestKit_Software_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?TestKit_Software_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory ?TestKit_Software_DataProvider_Category . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDescription ?TestKit_Software_Description . }
    optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasVersion ?TestKit_Software_Version . }
    optional{ ?resource sphn:hasTestKit/sphn:hasProductCode ?TestKit_ProductCode . }
    optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasName ?TestKit_ProductCode_Name . }
    optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasIdentifier ?TestKit_ProductCode_Identifier . }
    optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?TestKit_ProductCode_CodingSystemAndVersion . }

}