PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MedicalDevice> .
    optional{ ?resource sphn:hasTypeCode ?TypeCode . }
    optional{ ?resource sphn:hasTypeCode/sphn:hasName ?TypeCode_Name . }
    optional{ ?resource sphn:hasTypeCode/sphn:hasIdentifier ?TypeCode_Identifier . }
    optional{ ?resource sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?TypeCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSoftware ?Software . }
    optional{ ?resource sphn:hasSoftware/sphn:hasName ?Software_Name . }
    optional{ ?resource sphn:hasSoftware/sphn:hasUniformResourceLocator ?Software_UniformResourceLocator . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDataProvider ?Software_DataProvider . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment ?Software_DataProvider_Department . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Software_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?Software_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Software_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Software_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Software_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory ?Software_DataProvider_Category . }
    optional{ ?resource sphn:hasSoftware/sphn:hasDescription ?Software_Description . }
    optional{ ?resource sphn:hasSoftware/sphn:hasVersion ?Software_Version . }
    optional{ ?resource sphn:hasProductCode ?ProductCode . }
    optional{ ?resource sphn:hasProductCode/sphn:hasName ?ProductCode_Name . }
    optional{ ?resource sphn:hasProductCode/sphn:hasIdentifier ?ProductCode_Identifier . }
    optional{ ?resource sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?ProductCode_CodingSystemAndVersion . }

}