PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicroorganismIdentificationResult> .
    optional{ ?resource sphn:hasCode ?Code . }
    optional{ ?resource sphn:hasTimeToPositivity ?TimeToPositivity . }
    optional{ ?resource sphn:hasTimeToPositivity/sphn:hasValue ?TimeToPositivity_Value . }
    optional{ ?resource sphn:hasTimeToPositivity/sphn:hasUnit ?TimeToPositivity_Unit . }
    optional{ ?resource sphn:hasTimeToPositivity/sphn:hasUnit/sphn:hasCode ?TimeToPositivity_Unit_Code . }
    optional{ ?resource sphn:hasTimeToPositivity/sphn:hasComparator ?TimeToPositivity_Comparator . }
    optional{ ?resource sphn:hasStringValue ?StringValue . }
    optional{ ?resource sphn:hasOrganism ?Organism . }
    optional{ ?resource sphn:hasOrganism/sphn:hasCode ?Organism_Code . }
    optional{ ?resource sphn:hasOrganism/sphn:hasCode/sphn:hasName ?Organism_Code_Name . }
    optional{ ?resource sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier ?Organism_Code_Identifier . }
    optional{ ?resource sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion ?Organism_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasNumericalReference ?NumericalReference . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity ?NumericalReference_Quantity . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasValue ?NumericalReference_Quantity_Value . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit ?NumericalReference_Quantity_Unit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?NumericalReference_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasComparator ?NumericalReference_Quantity_Comparator . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit ?NumericalReference_LowerLimit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasValue ?NumericalReference_LowerLimit_Value . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit ?NumericalReference_LowerLimit_Unit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode ?NumericalReference_LowerLimit_Unit_Code . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasComparator ?NumericalReference_LowerLimit_Comparator . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit ?NumericalReference_UpperLimit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasValue ?NumericalReference_UpperLimit_Value . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit ?NumericalReference_UpperLimit_Unit . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode ?NumericalReference_UpperLimit_Unit_Code . }
    optional{ ?resource sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasComparator ?NumericalReference_UpperLimit_Comparator . }

}