PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicroorganismIdentificationLabTestEvent> .
    optional{ ?resource sphn:hasDateTime ?DateTime . }
    optional{ ?resource sphn:hasDataProvider ?DataProvider . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment ?DataProvider_Department . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode ?DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasCategory ?DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem ?SourceSystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasName ?SourceSystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider ?SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem ?SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasCategory ?SourceSystem_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPurpose ?SourceSystem_Purpose . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier ?SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase ?AdministrativeCase . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime ?AdministrativeCase_AdmissionDateTime . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeDateTime ?AdministrativeCase_DischargeDateTime . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasIdentifier ?AdministrativeCase_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider ?AdministrativeCase_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling ?AdministrativeCase_CareHandling . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem ?AdministrativeCase_CareHandling_SourceSystem . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider ?AdministrativeCase_CareHandling_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_CareHandling_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasCategory ?AdministrativeCase_CareHandling_SourceSystem_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPurpose ?AdministrativeCase_CareHandling_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasTypeCode ?AdministrativeCase_CareHandling_TypeCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation ?AdministrativeCase_DischargeLocation . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasExact ?AdministrativeCase_DischargeLocation_Exact . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider ?AdministrativeCase_DischargeLocation_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_DischargeLocation_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_DischargeLocation_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_DischargeLocation_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasTypeCode ?AdministrativeCase_DischargeLocation_TypeCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem ?AdministrativeCase_SourceSystem . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasName ?AdministrativeCase_SourceSystem_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider ?AdministrativeCase_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem ?AdministrativeCase_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?AdministrativeCase_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?AdministrativeCase_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasCategory ?AdministrativeCase_SourceSystem_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPurpose ?AdministrativeCase_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier ?AdministrativeCase_SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?AdministrativeCase_SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?AdministrativeCase_SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation ?AdministrativeCase_OriginLocation . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasExact ?AdministrativeCase_OriginLocation_Exact . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider ?AdministrativeCase_OriginLocation_DataProvider . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasDepartment ?AdministrativeCase_OriginLocation_DataProvider_Department . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?AdministrativeCase_OriginLocation_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode ?AdministrativeCase_OriginLocation_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasCategory ?AdministrativeCase_OriginLocation_DataProvider_Category . }
    optional{ ?resource sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasTypeCode ?AdministrativeCase_OriginLocation_TypeCode . }
    optional{ ?resource sphn:hasLabTest ?LabTest . }
    optional{ ?resource sphn:hasLabTest/sphn:hasCode ?LabTest_Code . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult ?LabTest_Result . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasCode ?LabTest_Result_Code . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasTimeToPositivity ?LabTest_Result_TimeToPositivity . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasTimeToPositivity/sphn:hasValue ?LabTest_Result_TimeToPositivity_Value . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasTimeToPositivity/sphn:hasUnit ?LabTest_Result_TimeToPositivity_Unit . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasTimeToPositivity/sphn:hasUnit/sphn:hasCode ?LabTest_Result_TimeToPositivity_Unit_Code . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasTimeToPositivity/sphn:hasComparator ?LabTest_Result_TimeToPositivity_Comparator . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasStringValue ?LabTest_Result_StringValue . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasOrganism ?LabTest_Result_Organism . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasOrganism/sphn:hasCode ?LabTest_Result_Organism_Code . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasOrganism/sphn:hasCode/sphn:hasName ?LabTest_Result_Organism_Code_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier ?LabTest_Result_Organism_Code_Identifier . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion ?LabTest_Result_Organism_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference ?LabTest_Result_NumericalReference . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity ?LabTest_Result_NumericalReference_Quantity . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasValue ?LabTest_Result_NumericalReference_Quantity_Value . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit ?LabTest_Result_NumericalReference_Quantity_Unit . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?LabTest_Result_NumericalReference_Quantity_Unit_Code . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasComparator ?LabTest_Result_NumericalReference_Quantity_Comparator . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit ?LabTest_Result_NumericalReference_LowerLimit . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasValue ?LabTest_Result_NumericalReference_LowerLimit_Value . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit ?LabTest_Result_NumericalReference_LowerLimit_Unit . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode ?LabTest_Result_NumericalReference_LowerLimit_Unit_Code . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasComparator ?LabTest_Result_NumericalReference_LowerLimit_Comparator . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit ?LabTest_Result_NumericalReference_UpperLimit . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasValue ?LabTest_Result_NumericalReference_UpperLimit_Value . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit ?LabTest_Result_NumericalReference_UpperLimit_Unit . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode ?LabTest_Result_NumericalReference_UpperLimit_Unit_Code . }
    optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasComparator ?LabTest_Result_NumericalReference_UpperLimit_Comparator . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument ?LabTest_Instrument . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasTypeCode ?LabTest_Instrument_TypeCode . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasTypeCode/sphn:hasName ?LabTest_Instrument_TypeCode_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasTypeCode/sphn:hasIdentifier ?LabTest_Instrument_TypeCode_Identifier . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?LabTest_Instrument_TypeCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware ?LabTest_Instrument_Software . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasName ?LabTest_Instrument_Software_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasUniformResourceLocator ?LabTest_Instrument_Software_UniformResourceLocator . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider ?LabTest_Instrument_Software_DataProvider . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment ?LabTest_Instrument_Software_DataProvider_Department . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?LabTest_Instrument_Software_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?LabTest_Instrument_Software_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?LabTest_Instrument_Software_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?LabTest_Instrument_Software_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?LabTest_Instrument_Software_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory ?LabTest_Instrument_Software_DataProvider_Category . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasDescription ?LabTest_Instrument_Software_Description . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasSoftware/sphn:hasVersion ?LabTest_Instrument_Software_Version . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasProductCode ?LabTest_Instrument_ProductCode . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasProductCode/sphn:hasName ?LabTest_Instrument_ProductCode_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasProductCode/sphn:hasIdentifier ?LabTest_Instrument_ProductCode_Identifier . }
    optional{ ?resource sphn:hasLabTest/sphn:hasInstrument/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?LabTest_Instrument_ProductCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit ?LabTest_TestKit . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasTypeCode ?LabTest_TestKit_TypeCode . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasTypeCode/sphn:hasName ?LabTest_TestKit_TypeCode_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasTypeCode/sphn:hasIdentifier ?LabTest_TestKit_TypeCode_Identifier . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?LabTest_TestKit_TypeCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware ?LabTest_TestKit_Software . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasName ?LabTest_TestKit_Software_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasUniformResourceLocator ?LabTest_TestKit_Software_UniformResourceLocator . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider ?LabTest_TestKit_Software_DataProvider . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment ?LabTest_TestKit_Software_DataProvider_Department . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?LabTest_TestKit_Software_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?LabTest_TestKit_Software_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?LabTest_TestKit_Software_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?LabTest_TestKit_Software_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?LabTest_TestKit_Software_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory ?LabTest_TestKit_Software_DataProvider_Category . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasDescription ?LabTest_TestKit_Software_Description . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasSoftware/sphn:hasVersion ?LabTest_TestKit_Software_Version . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasProductCode ?LabTest_TestKit_ProductCode . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasProductCode/sphn:hasName ?LabTest_TestKit_ProductCode_Name . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasProductCode/sphn:hasIdentifier ?LabTest_TestKit_ProductCode_Identifier . }
    optional{ ?resource sphn:hasLabTest/sphn:hasTestKit/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?LabTest_TestKit_ProductCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample ?Sample . }
    optional{ ?resource sphn:hasSample/sphn:hasSharedIdentifier ?Sample_SharedIdentifier . }
    optional{ ?resource sphn:hasSample/sphn:hasIdentifier ?Sample_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasDataProvider ?Sample_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasDataProvider/sphn:hasDepartment ?Sample_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasDataProvider/sphn:hasCategory ?Sample_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasBodySite ?Sample_BodySite . }
    optional{ ?resource sphn:hasSample/sphn:hasBodySite/sphn:hasCode ?Sample_BodySite_Code . }
    optional{ ?resource sphn:hasSample/sphn:hasBodySite/sphn:hasLaterality ?Sample_BodySite_Laterality . }
    optional{ ?resource sphn:hasSample/sphn:hasBodySite/sphn:hasLaterality/sphn:hasCode ?Sample_BodySite_Laterality_Code . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem ?Sample_SourceSystem . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasName ?Sample_SourceSystem_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasDataProvider ?Sample_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?Sample_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?Sample_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem ?Sample_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?Sample_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?Sample_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?Sample_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?Sample_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?Sample_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasCategory ?Sample_SourceSystem_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasSourceSystem/sphn:hasPurpose ?Sample_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier ?Sample_SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?Sample_SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?Sample_SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?Sample_SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?Sample_SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?Sample_SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasCollectionDateTime ?Sample_CollectionDateTime . }
    optional{ ?resource sphn:hasSample/sphn:hasMaterialTypeCode ?Sample_MaterialTypeCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase ?Sample_AdministrativeCase . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime ?Sample_AdministrativeCase_AdmissionDateTime . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeDateTime ?Sample_AdministrativeCase_DischargeDateTime . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasIdentifier ?Sample_AdministrativeCase_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDataProvider ?Sample_AdministrativeCase_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasDepartment ?Sample_AdministrativeCase_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_AdministrativeCase_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_AdministrativeCase_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_AdministrativeCase_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_AdministrativeCase_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_AdministrativeCase_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasCategory ?Sample_AdministrativeCase_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling ?Sample_AdministrativeCase_CareHandling . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem ?Sample_AdministrativeCase_CareHandling_SourceSystem . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasName ?Sample_AdministrativeCase_CareHandling_SourceSystem_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider ?Sample_AdministrativeCase_CareHandling_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?Sample_AdministrativeCase_CareHandling_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_AdministrativeCase_CareHandling_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?Sample_AdministrativeCase_CareHandling_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?Sample_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasCategory ?Sample_AdministrativeCase_CareHandling_SourceSystem_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPurpose ?Sample_AdministrativeCase_CareHandling_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasTypeCode ?Sample_AdministrativeCase_CareHandling_TypeCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation ?Sample_AdministrativeCase_DischargeLocation . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasExact ?Sample_AdministrativeCase_DischargeLocation_Exact . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider ?Sample_AdministrativeCase_DischargeLocation_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasDepartment ?Sample_AdministrativeCase_DischargeLocation_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_AdministrativeCase_DischargeLocation_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasCategory ?Sample_AdministrativeCase_DischargeLocation_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasTypeCode ?Sample_AdministrativeCase_DischargeLocation_TypeCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem ?Sample_AdministrativeCase_SourceSystem . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasName ?Sample_AdministrativeCase_SourceSystem_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider ?Sample_AdministrativeCase_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?Sample_AdministrativeCase_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_AdministrativeCase_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_AdministrativeCase_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?Sample_AdministrativeCase_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem ?Sample_AdministrativeCase_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?Sample_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasCategory ?Sample_AdministrativeCase_SourceSystem_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPurpose ?Sample_AdministrativeCase_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier ?Sample_AdministrativeCase_SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?Sample_AdministrativeCase_SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?Sample_AdministrativeCase_SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?Sample_AdministrativeCase_SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?Sample_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?Sample_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation ?Sample_AdministrativeCase_OriginLocation . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasExact ?Sample_AdministrativeCase_OriginLocation_Exact . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider ?Sample_AdministrativeCase_OriginLocation_DataProvider . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasDepartment ?Sample_AdministrativeCase_OriginLocation_DataProvider_Department . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Sample_AdministrativeCase_OriginLocation_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode ?Sample_AdministrativeCase_OriginLocation_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Sample_AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Sample_AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Sample_AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasCategory ?Sample_AdministrativeCase_OriginLocation_DataProvider_Category . }
    optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasTypeCode ?Sample_AdministrativeCase_OriginLocation_TypeCode . }
    optional{ ?resource sphn:hasSample/sphn:hasFixationType ?Sample_FixationType . }
    optional{ ?resource sphn:hasSample/sphn:hasPrimaryContainer ?Sample_PrimaryContainer . }
    optional{ ?resource sphn:hasReportDateTime ?ReportDateTime . }

}