PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#Protein> .
    optional{ ?resource sphn:hasCode ?Code . }
    optional{ ?resource sphn:hasCode/sphn:hasName ?Code_Name . }
    optional{ ?resource sphn:hasCode/sphn:hasIdentifier ?Code_Identifier . }
    optional{ ?resource sphn:hasCode/sphn:hasCodingSystemAndVersion ?Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasOrganism ?Organism . }
    optional{ ?resource sphn:hasOrganism/sphn:hasCode ?Organism_Code . }
    optional{ ?resource sphn:hasOrganism/sphn:hasCode/sphn:hasName ?Organism_Code_Name . }
    optional{ ?resource sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier ?Organism_Code_Identifier . }
    optional{ ?resource sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion ?Organism_Code_CodingSystemAndVersion . }

}