PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SemanticMapping> .
    optional{ ?resource sphn:hasDateTime ?DateTime . }
    optional{ ?resource sphn:hasOutputCode ?OutputCode . }
    optional{ ?resource sphn:hasOutputCode/sphn:hasName ?OutputCode_Name . }
    optional{ ?resource sphn:hasOutputCode/sphn:hasIdentifier ?OutputCode_Identifier . }
    optional{ ?resource sphn:hasOutputCode/sphn:hasCodingSystemAndVersion ?OutputCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceData ?SourceData . }
    optional{ ?resource sphn:hasSourceData/sphn:hasCode ?SourceData_Code . }
    optional{ ?resource sphn:hasSourceData/sphn:hasCode/sphn:hasName ?SourceData_Code_Name . }
    optional{ ?resource sphn:hasSourceData/sphn:hasCode/sphn:hasIdentifier ?SourceData_Code_Identifier . }
    optional{ ?resource sphn:hasSourceData/sphn:hasCode/sphn:hasCodingSystemAndVersion ?SourceData_Code_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem ?SourceData_SourceSystem . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasName ?SourceData_SourceSystem_Name . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasDataProvider ?SourceData_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceData_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceData_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceData_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceData_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceData_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceData_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?SourceData_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem ?SourceData_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?SourceData_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?SourceData_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?SourceData_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceData_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceData_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceData_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceData_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceData_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceData_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?SourceData_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasCategory ?SourceData_SourceSystem_Category . }
    optional{ ?resource sphn:hasSourceData/sphn:hasSourceSystem/sphn:hasPurpose ?SourceData_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasSourceData/sphn:hasStringValue ?SourceData_StringValue . }
    optional{ ?resource sphn:hasDataProvider ?DataProvider . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment ?DataProvider_Department . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode ?DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasCategory ?DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem ?SourceSystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasName ?SourceSystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider ?SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem ?SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasCategory ?SourceSystem_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPurpose ?SourceSystem_Purpose . }
    optional{ ?resource sphn:hasMethodCode ?MethodCode . }
    optional{ ?resource sphn:hasPurpose ?Purpose . }

}