PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#StandardOperatingProcedure> .
    optional{ ?resource sphn:hasName ?Name . }
    optional{ ?resource sphn:hasDataProvider ?DataProvider . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment ?DataProvider_Department . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode ?DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasCategory ?DataProvider_Category . }
    optional{ ?resource sphn:hasDataFile ?DataFile . }
    optional{ ?resource sphn:hasDataFile/sphn:hasName ?DataFile_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasDataProvider ?DataFile_DataProvider . }
    optional{ ?resource sphn:hasDataFile/sphn:hasDataProvider/sphn:hasDepartment ?DataFile_DataProvider_Department . }
    optional{ ?resource sphn:hasDataFile/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataFile_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasDataProvider/sphn:hasInstitutionCode ?DataFile_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataFile/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataFile_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataFile_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataFile/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataFile_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataFile/sphn:hasDataProvider/sphn:hasCategory ?DataFile_DataProvider_Category . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem ?DataFile_SourceSystem . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasName ?DataFile_SourceSystem_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasDataProvider ?DataFile_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?DataFile_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataFile_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?DataFile_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataFile_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataFile_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataFile_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?DataFile_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem ?DataFile_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?DataFile_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?DataFile_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?DataFile_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?DataFile_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataFile_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?DataFile_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataFile_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataFile_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataFile_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?DataFile_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasCategory ?DataFile_SourceSystem_Category . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSourceSystem/sphn:hasPurpose ?DataFile_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasDataFile/sphn:hasCreationDateTime ?DataFile_CreationDateTime . }
    optional{ ?resource sphn:hasDataFile/sphn:hasUniformResourceIdentifier ?DataFile_UniformResourceIdentifier . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier ?DataFile_SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?DataFile_SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?DataFile_SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?DataFile_SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?DataFile_SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataFile_SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?DataFile_SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataFile_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataFile_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataFile_SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataFile/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?DataFile_SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasDataFile/sphn:hasEncoding ?DataFile_Encoding . }
    optional{ ?resource sphn:hasDataFile/sphn:hasFormatCode ?DataFile_FormatCode . }
    optional{ ?resource sphn:hasDataFile/sphn:hasHash ?DataFile_Hash . }
    optional{ ?resource sphn:hasDataFile/sphn:hasHash/sphn:hasAlgorithm ?DataFile_Hash_Algorithm . }
    optional{ ?resource sphn:hasDataFile/sphn:hasHash/sphn:hasStringValue ?DataFile_Hash_StringValue . }
    optional{ ?resource sphn:hasDescription ?Description . }
    optional{ ?resource sphn:hasVersion ?Version . }

}