PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SubjectPseudoIdentifier> .
    optional{ ?resource sphn:hasSharedIdentifier ?SharedIdentifier . }
    optional{ ?resource sphn:hasIdentifier ?Identifier . }
    optional{ ?resource sphn:hasDataProvider ?DataProvider . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment ?DataProvider_Department . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode ?DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasCategory ?DataProvider_Category . }

}