PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#VitalStatus> .
    optional{ ?resource sphn:hasCode ?Code . }
    optional{ ?resource sphn:hasDataProvider ?DataProvider . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment ?DataProvider_Department . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode ?DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDataProvider/sphn:hasCategory ?DataProvider_Category . }
    optional{ ?resource sphn:hasDeath ?Death . }
    optional{ ?resource sphn:hasDeath/sphn:hasDataProvider ?Death_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasDataProvider/sphn:hasDepartment ?Death_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasDataProvider/sphn:hasCategory ?Death_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasCircumstanceCode ?Death_CircumstanceCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasConditionCode ?Death_ConditionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem ?Death_SourceSystem . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasName ?Death_SourceSystem_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasDataProvider ?Death_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?Death_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?Death_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem ?Death_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?Death_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?Death_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?Death_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?Death_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?Death_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasCategory ?Death_SourceSystem_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasSourceSystem/sphn:hasPurpose ?Death_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier ?Death_SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?Death_SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?Death_SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?Death_SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?Death_SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?Death_SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate ?Death_Date . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDataProvider ?Death_Date_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDataProvider/sphn:hasDepartment ?Death_Date_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_Date_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_Date_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_Date_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_Date_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_Date_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDataProvider/sphn:hasCategory ?Death_Date_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem ?Death_Date_SourceSystem . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasName ?Death_Date_SourceSystem_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasDataProvider ?Death_Date_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?Death_Date_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_Date_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_Date_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_Date_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_Date_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_Date_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?Death_Date_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem ?Death_Date_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?Death_Date_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?Death_Date_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?Death_Date_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?Death_Date_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_Date_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_Date_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_Date_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_Date_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_Date_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?Death_Date_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasCategory ?Death_Date_SourceSystem_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSourceSystem/sphn:hasPurpose ?Death_Date_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasDay ?Death_Date_Day . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasMonth ?Death_Date_Month . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasTime ?Death_Date_Time . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasYear ?Death_Date_Year . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier ?Death_Date_SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?Death_Date_SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?Death_Date_SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?Death_Date_SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?Death_Date_SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_Date_SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_Date_SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_Date_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_Date_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_Date_SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasDate/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?Death_Date_SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase ?Death_AdministrativeCase . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime ?Death_AdministrativeCase_AdmissionDateTime . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeDateTime ?Death_AdministrativeCase_DischargeDateTime . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasIdentifier ?Death_AdministrativeCase_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDataProvider ?Death_AdministrativeCase_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasDepartment ?Death_AdministrativeCase_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_AdministrativeCase_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_AdministrativeCase_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_AdministrativeCase_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_AdministrativeCase_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_AdministrativeCase_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDataProvider/sphn:hasCategory ?Death_AdministrativeCase_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling ?Death_AdministrativeCase_CareHandling . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem ?Death_AdministrativeCase_CareHandling_SourceSystem . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasName ?Death_AdministrativeCase_CareHandling_SourceSystem_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider ?Death_AdministrativeCase_CareHandling_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?Death_AdministrativeCase_CareHandling_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_AdministrativeCase_CareHandling_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_AdministrativeCase_CareHandling_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?Death_AdministrativeCase_CareHandling_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?Death_AdministrativeCase_CareHandling_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasCategory ?Death_AdministrativeCase_CareHandling_SourceSystem_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasSourceSystem/sphn:hasPurpose ?Death_AdministrativeCase_CareHandling_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasCareHandling/sphn:hasTypeCode ?Death_AdministrativeCase_CareHandling_TypeCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation ?Death_AdministrativeCase_DischargeLocation . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasExact ?Death_AdministrativeCase_DischargeLocation_Exact . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider ?Death_AdministrativeCase_DischargeLocation_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasDepartment ?Death_AdministrativeCase_DischargeLocation_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_AdministrativeCase_DischargeLocation_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_AdministrativeCase_DischargeLocation_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasDataProvider/sphn:hasCategory ?Death_AdministrativeCase_DischargeLocation_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasDischargeLocation/sphn:hasTypeCode ?Death_AdministrativeCase_DischargeLocation_TypeCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem ?Death_AdministrativeCase_SourceSystem . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasName ?Death_AdministrativeCase_SourceSystem_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider ?Death_AdministrativeCase_SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?Death_AdministrativeCase_SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_AdministrativeCase_SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_AdministrativeCase_SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_AdministrativeCase_SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?Death_AdministrativeCase_SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem ?Death_AdministrativeCase_SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?Death_AdministrativeCase_SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?Death_AdministrativeCase_SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?Death_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?Death_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?Death_AdministrativeCase_SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasCategory ?Death_AdministrativeCase_SourceSystem_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSourceSystem/sphn:hasPurpose ?Death_AdministrativeCase_SourceSystem_Purpose . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier ?Death_AdministrativeCase_SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?Death_AdministrativeCase_SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?Death_AdministrativeCase_SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?Death_AdministrativeCase_SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?Death_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?Death_AdministrativeCase_SubjectPseudoIdentifier_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation ?Death_AdministrativeCase_OriginLocation . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasExact ?Death_AdministrativeCase_OriginLocation_Exact . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider ?Death_AdministrativeCase_OriginLocation_DataProvider . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasDepartment ?Death_AdministrativeCase_OriginLocation_DataProvider_Department . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?Death_AdministrativeCase_OriginLocation_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode ?Death_AdministrativeCase_OriginLocation_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?Death_AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?Death_AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?Death_AdministrativeCase_OriginLocation_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasDataProvider/sphn:hasCategory ?Death_AdministrativeCase_OriginLocation_DataProvider_Category . }
    optional{ ?resource sphn:hasDeath/sphn:hasAdministrativeCase/sphn:hasOriginLocation/sphn:hasTypeCode ?Death_AdministrativeCase_OriginLocation_TypeCode . }
    optional{ ?resource sphn:hasDeath/sphn:hasReportDateTime ?Death_ReportDateTime . }
    optional{ ?resource sphn:hasSourceSystem ?SourceSystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasName ?SourceSystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider ?SourceSystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem ?SourceSystem_PrimarySystem . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasName ?SourceSystem_PrimarySystem_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?SourceSystem_PrimarySystem_Code . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider ?SourceSystem_PrimarySystem_DataProvider . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment ?SourceSystem_PrimarySystem_DataProvider_Department . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SourceSystem_PrimarySystem_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasCategory ?SourceSystem_PrimarySystem_DataProvider_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasCategory ?SourceSystem_Category . }
    optional{ ?resource sphn:hasSourceSystem/sphn:hasPurpose ?SourceSystem_Purpose . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier ?SubjectPseudoIdentifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasSharedIdentifier ?SubjectPseudoIdentifier_SharedIdentifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasIdentifier ?SubjectPseudoIdentifier_Identifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider ?SubjectPseudoIdentifier_DataProvider . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment ?SubjectPseudoIdentifier_DataProvider_Department . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?SubjectPseudoIdentifier_DataProvider_Department_Name . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode ?SubjectPseudoIdentifier_DataProvider_InstitutionCode . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_Name . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_Identifier . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?SubjectPseudoIdentifier_DataProvider_InstitutionCode_CodingSystemAndVersion . }
    optional{ ?resource sphn:hasSubjectPseudoIdentifier/sphn:hasDataProvider/sphn:hasCategory ?SubjectPseudoIdentifier_DataProvider_Category . }

}