PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#BirthDate> .

        BIND("sphn:hasDay" as ?origin)
        optional{ ?resource sphn:hasDay ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#BirthDate> .

        BIND("sphn:hasMonth" as ?origin)
        optional{ ?resource sphn:hasMonth ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#BirthDate> .

        BIND("sphn:hasTime" as ?origin)
        optional{ ?resource sphn:hasTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#BirthDate> .

        BIND("sphn:hasYear" as ?origin)
        optional{ ?resource sphn:hasYear ?value . }

    }
    GROUP BY ?origin
    }

}