PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasFirstAdministrationDateTime" as ?origin)
        optional{ ?resource sphn:hasFirstAdministrationDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasRecordDateTime" as ?origin)
        optional{ ?resource sphn:hasRecordDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasIndicationToStart/sphn:hasRecordDateTime" as ?origin)
        optional{ ?resource sphn:hasIndicationToStart/sphn:hasRecordDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasIndicationToStart/sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime" as ?origin)
        optional{ ?resource sphn:hasIndicationToStart/sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasIndicationToStart/sphn:hasAdministrativeCase/sphn:hasDischargeDateTime" as ?origin)
        optional{ ?resource sphn:hasIndicationToStart/sphn:hasAdministrativeCase/sphn:hasDischargeDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasIndicationToStart/sphn:hasSubjectAge/sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasIndicationToStart/sphn:hasSubjectAge/sphn:hasQuantity/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasIndicationToStart/sphn:hasSubjectAge/sphn:hasDeterminationDateTime" as ?origin)
        optional{ ?resource sphn:hasIndicationToStart/sphn:hasSubjectAge/sphn:hasDeterminationDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasLastAdministrationDateTime" as ?origin)
        optional{ ?resource sphn:hasLastAdministrationDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasFrequency/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasFrequency/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasDrug/sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasDrug/sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasDrug/sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasDrug/sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasDrug/sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasDrug/sphn:hasQuantity/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime" as ?origin)
        optional{ ?resource sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#DrugPrescription> .

        BIND("sphn:hasAdministrativeCase/sphn:hasDischargeDateTime" as ?origin)
        optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeDateTime ?value . }

    }
    GROUP BY ?origin
    }

}