PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasDateTime" as ?origin)
        optional{ ?resource sphn:hasDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime" as ?origin)
        optional{ ?resource sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasAdministrativeCase/sphn:hasDischargeDateTime" as ?origin)
        optional{ ?resource sphn:hasAdministrativeCase/sphn:hasDischargeDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasLabTest/sphn:hasResult/sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasQuantity/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasLabTest/sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasSample/sphn:hasCollectionDateTime" as ?origin)
        optional{ ?resource sphn:hasSample/sphn:hasCollectionDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime" as ?origin)
        optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasAdmissionDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeDateTime" as ?origin)
        optional{ ?resource sphn:hasSample/sphn:hasAdministrativeCase/sphn:hasDischargeDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTestEvent> .

        BIND("sphn:hasReportDateTime" as ?origin)
        optional{ ?resource sphn:hasReportDateTime ?value . }

    }
    GROUP BY ?origin
    }

}