PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#OxygenSaturation> .

        BIND("sphn:hasDateTime" as ?origin)
        optional{ ?resource sphn:hasDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#OxygenSaturation> .

        BIND("sphn:hasDataFile/sphn:hasCreationDateTime" as ?origin)
        optional{ ?resource sphn:hasDataFile/sphn:hasCreationDateTime ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#OxygenSaturation> .

        BIND("sphn:hasDataFile/sphn:hasEntryCount/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasDataFile/sphn:hasEntryCount/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }
        UNION
    {
    SELECT ?origin (MIN(?value) as ?min) (MAX(?value) as ?max)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#OxygenSaturation> .

        BIND("sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasQuantity/sphn:hasValue ?value . }

    }
    GROUP BY ?origin
    }

}