PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasCode ?code . }
        optional{ ?resource sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasActiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasInactiveIngredient/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasManufacturedDoseForm/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasArticle/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasChemicalAgent/sphn:hasSourceSystem/sphn:hasPrimarySystem/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasResult/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasResult/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode ?code . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasInstrument/sphn:hasTypeCode" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode ?code . }
        optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasInstrument/sphn:hasProductCode" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasProductCode ?code . }
        optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasTestKit/sphn:hasTypeCode" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode ?code . }
        optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?code . }
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }
        UNION
    {
    SELECT ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion (COUNT(?code) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#AntimicrobialSusceptibilityLabTest> .

        BIND("sphn:hasTestKit/sphn:hasProductCode" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasProductCode ?code . }
        optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasIdentifier ?code_identifier . }
        optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasName ?code_name . }
        optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?code_codingSystemAndVersion . }

    }
    GROUP BY ?origin ?code ?code_identifier ?code_name ?code_codingSystemAndVersion
    }

}