PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    {
    SELECT ?origin (COUNT(?origin) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .
        BIND("https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest" as ?origin)
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasTranscript/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasProtein/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTargetMolecule/sphn:hasOrganism/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult" as ?origin)
        optional{ ?resource sphn:hasResult ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasQuantity" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasQuantity ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasValue ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasQuantity/sphn:hasUnit" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasQuantity/sphn:hasComparator" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasQuantity/sphn:hasComparator ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasStringValue" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasStringValue ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasValue ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasUnit/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasComparator" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasQuantity/sphn:hasComparator ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasValue ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasUnit/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasComparator" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasLowerLimit/sphn:hasComparator ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasValue ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasUnit/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasComparator" as ?origin)
        optional{ ?resource sphn:hasResult/sphn:hasNumericalReference/sphn:hasUpperLimit/sphn:hasComparator ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument" as ?origin)
        optional{ ?resource sphn:hasInstrument ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasTypeCode" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasTypeCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasTypeCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasUniformResourceLocator" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasUniformResourceLocator ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasDescription" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasDescription ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasSoftware/sphn:hasVersion" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasSoftware/sphn:hasVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasProductCode" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasProductCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasProductCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasProductCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasInstrument/sphn:hasProductCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasInstrument/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit" as ?origin)
        optional{ ?resource sphn:hasTestKit ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasTypeCode" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasTypeCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasTypeCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasTypeCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasUniformResourceLocator" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasUniformResourceLocator ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasDepartment/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasInstitutionCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDataProvider/sphn:hasCategory ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasDescription" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasDescription ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasSoftware/sphn:hasVersion" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasSoftware/sphn:hasVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasProductCode" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasProductCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasProductCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasProductCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#MicrobiologyBiomoleculePresenceLabTest> .

        BIND("sphn:hasTestKit/sphn:hasProductCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasTestKit/sphn:hasProductCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
}}