PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    {
    SELECT ?origin (COUNT(?origin) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .
        BIND("https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation" as ?origin)
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasAlternateAllele" as ?origin)
        optional{ ?resource sphn:hasAlternateAllele ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasReferenceAllele" as ?origin)
        optional{ ?resource sphn:hasReferenceAllele ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition/sphn:hasEnd" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition/sphn:hasEnd ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition/sphn:hasStart" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition/sphn:hasStart ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition/sphn:hasCoordinateConvention" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition/sphn:hasCoordinateConvention ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition/sphn:hasReference" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition/sphn:hasReference ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition/sphn:hasReference/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition/sphn:hasReference/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition/sphn:hasReference/sphn:hasCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition/sphn:hasReference/sphn:hasCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition/sphn:hasReference/sphn:hasCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition/sphn:hasReference/sphn:hasCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasGenomicPosition/sphn:hasReference/sphn:hasCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasGenomicPosition/sphn:hasReference/sphn:hasCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasChromosome" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasChromosome ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasChromosome/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasChromosome/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasEndCytobandCode" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasEndCytobandCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasEndCytobandCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasEndCytobandCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasEndCytobandCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasEndCytobandCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasEndCytobandCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasEndCytobandCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasStartCytobandCode" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasStartCytobandCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasStartCytobandCode/sphn:hasName" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasStartCytobandCode/sphn:hasName ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasStartCytobandCode/sphn:hasIdentifier" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasStartCytobandCode/sphn:hasIdentifier ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SingleNucleotideVariation> .

        BIND("sphn:hasChromosomalLocation/sphn:hasStartCytobandCode/sphn:hasCodingSystemAndVersion" as ?origin)
        optional{ ?resource sphn:hasChromosomalLocation/sphn:hasStartCytobandCode/sphn:hasCodingSystemAndVersion ?predicate . }
    }
    GROUP BY ?origin
}}