PREFIX sphn:<https://biomedit.ch/rdf/sphn-schema/sphn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
    {
    SELECT ?origin (COUNT(?origin) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition> .
        BIND("https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition" as ?origin)
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition> .

        BIND("sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasValue ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition> .

        BIND("sphn:hasDistance" as ?origin)
        optional{ ?resource sphn:hasDistance ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition> .

        BIND("sphn:hasDistance/sphn:hasValue" as ?origin)
        optional{ ?resource sphn:hasDistance/sphn:hasValue ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition> .

        BIND("sphn:hasDistance/sphn:hasUnit" as ?origin)
        optional{ ?resource sphn:hasDistance/sphn:hasUnit ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition> .

        BIND("sphn:hasDistance/sphn:hasUnit/sphn:hasCode" as ?origin)
        optional{ ?resource sphn:hasDistance/sphn:hasUnit/sphn:hasCode ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition> .

        BIND("sphn:hasDistance/sphn:hasComparator" as ?origin)
        optional{ ?resource sphn:hasDistance/sphn:hasComparator ?predicate . }
    }
    GROUP BY ?origin
    } UNION
    {
    SELECT ?origin (COUNT(?predicate) as ?count_instances)
    WHERE {
        ?resource a <https://biomedit.ch/rdf/sphn-schema/sphn#SwissSocioEconomicPosition> .

        BIND("sphn:hasVersion" as ?origin)
        optional{ ?resource sphn:hasVersion ?predicate . }
    }
    GROUP BY ?origin
}}